spring:

  security:
      oauth2:
        client:
          registration:
            google:
              clientId: 804306916416-ukns44fu7qi6bl8kd4bpjk8mv4fnrmav.apps.googleusercontent.com
              clientSecret: gJNSTOhgZlx3X2IIp7lM-Qtb
              redirectUri: https://dlvery-deployment.herokuapp.com/oauth2/callback/google
              scope:
                - email
                - profile
 
app: 
  auth: 
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 604800 #864000000
  oauth2: 
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - https://dlvery-deployment.herokuapp.com/oauth2/redirect
      #- myandroidapp://oauth2/redirect
      #- myiosapp://oauth2/redirect